---
title: "Project Proposal"
description: |
  The title of our Project is "Visual analytics of GPS tracks: From Consumption to Relationship to Suspect Activity". We aims to get abnormal personal relationships based on the trajectory of all employees’ actions and consumption before the employees disappeared, so as to determine whether these people are related to the missing employees.We also hope to combine the relationship and gps traacks to get abnormal location so that we could estimate if something worth investigate at that place. Our application will inculding 4 parts, in each part we would gradually analyze the caracteristics of consumption and gps track and relationship. We hope to get abnormal location through all interactive graph.
author:
  - name: Wang Xiyu, Tang Huining
    url: https://scis.smu.edu.sg/
date: 08-15-2021
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Motivation

The driving record of the suspect has always been an important clue to most criminal cases. Through the analysis of the movement of individual people, we can find the suspect’s regular route and regular schedule which is the key in understanding patterns of their movements. Taking the GPS monitoring results of the company’s employees as a whole can help us understand whether the company has organized group activities at a specific time, such as company team building or overtime, which leads to unexpected group behavior. This helps the police find out the suspect’s unusual travel time and destination.
As for the credit card and loyalty card consumption records can help us find out whether the suspect has suspiciously large expenditures, and investigate whether it is possible to purchase suspicious items as criminal tools of crime through the location and name of business of the purchased items.

# Problem Statement

Explore relations among department, job title, travel time, main travel routes, and spending locations and amounts.
Explore spatial and time biases among department and job title, and similarities in traffic pattern and expenditure pattern.
Incorporate time series into consideration, build interactive visualizations to present traffic flow and traffic volume.
Further investigate the destination of travel and expenditure to derive insights about whether there is suspicious consumer behavior.


# Solution
To reveal the intuitive net work pattern, we will mainly use the ggraph package from R, which provides an flexible extension on the well-acclaimed ggplot2 package in R. In addition to providing the traffic flow between the various landmark nodes in the picture, we will also show the density of traffic, and provide users with visual detailed information through an interactive design.



